### ISSUE TITLE
Add an example of a Norikra query that returns human-readable date-time information

### ISSUE THREAD

**Issue by takuti** [takuti/datadog-anomaly-detector#2]
`SELECT (timestamp * 1000).format() as date` can be used, but it is not flexible enough in terms of timezone setting and formatting. 

Write Norikra/Esper UDF:
- https://github.com/norikra/norikra-udf-mock
- http://stackoverflow.com/questions/36281078/how-can-i-add-timezone-to-esper-queries

**Comment by myui** [comment]
BTW, human-like (?) human-readable?

**Comment by takuti** [comment]
One of the simplest ways to set timezone is that adding timestamp offset. For instance, JST is +9h from UTC, so it can be considered as:

``` sql
SELECT ((jst_timestamp + 60 * 60 * 9) * 1000).format() as d
...
```

Original output `8/10/16 4:39 AM` will be `8/10/16 1:39 PM` thanks to the offset.

Note: a field `jst_timestamp` represents UNIX time in a **second** range.

However, for more flexible configuration, UDF implementation is still important. It can be very similar to [MySQL's DATE_FORMAT function](https://dev.mysql.com/doc/refman/5.6/ja/date-and-time-functions.html#function_date-format). Idea:

``` sql
SELECT DATE_FORMAT(jst_timestamp * 1000, "yyyyMMdd/HHmmss", "JST") as d
...
```

**Comment by takuti** [comment]
Implemented this UDF https://github.com/takuti/norikra-udf-dateformat

**Comment by takuti** [comment]
The UDF successfully works on a production environment, and a sample query is available at https://github.com/takuti/datadog-anomaly-detector/blob/master/doc/norikra.md#2-add-a-filtering-query
