### ISSUE TITLE
Add dd snapshot url in each record

### ISSUE THREAD

**Issue by takuti** [takuti/datadog-anomaly-detector#7]
It can be obtained from: http://docs.datadoghq.com/api/#graph-snapshot

The URLs are used in slack notifications.

**Comment by myui** [comment]
By adding events, you can overlay events on snapshot.

http://docs.datadoghq.com/ja/api/#events
http://docs.datadoghq.com/api/#graph-snapshot
http://docs.datadoghq.com/guides/eventcorrelation/

**Comment by takuti** [comment]
@myui What kind of events should I overlay? Anomaly detection is done by Norikra-side, so the daemon script is only accessible to snapshots of the original metrics. Capturing a image of complex patterns detected by the CEP engine may require additional scripts in a middle of Norikra <-> Fluentd.

**Comment by myui** [comment]
@takuti 

Take a snapshot on the original metrics, not on the anomaly score metrics.

You can tag ranges of a single metric to a 10-min snapshot, e.g., on 
https://gyazo.com/93452649c7a26a6d153879ceadd468ec

Metrics are not combined there. 
2016-08-25 14:40 UTC and 2016-08-25 14:40 UTC should be tagged.

**Comment by takuti** [comment]
@myui OK, it seems to be easily implemented. 

Now each record holds snapshot urls as [here](https://github.com/takuti/datadog-anomaly-detector/blob/master/core/datadog_api_helper.py#L48-L53). By extending Norikra's `select` query, passing the url and displaying on slack is possible. Will be deployed and checked later.

**Comment by takuti** [comment]
@myui `query_snapshot` has API rate limit (60 per hour). So, unfortunatelly, passing the url in each record is unrealistic. https://help.datadoghq.com/hc/en-us/articles/205060139-API-rate-limit

**Comment by myui** [comment]
@takuti how about creating a safe (configurable) API limit on your application? 3(-5) API calls/hour or so.

**Comment by takuti** [comment]
OK, taking snapshots must be done on the fluent-plugin-side in practice. It's not this python-code-side issue.
