### ISSUE TITLE
Exception handling when Datadog API returned HTTP errors

### ISSUE THREAD

**Issue by myui** [takuti/datadog-anomaly-detector#9]
What will caused when Datadog API returns API outages or some errors? Daemon will down w/ errors?

Better to avoid tentative API errors and full error massages in log files and post a succinct error message to slack channel.

**Comment by takuti** [comment]
Currently [just raising an exception](https://github.com/takuti/datadog-anomaly-detector/blob/master/dd_anomaly_detector/datadog_api_helper.py#L20-L21), but it should be handled more carefully as you suggested.

In terms of logging: ref #5

**Comment by takuti** [comment]
Logging at [here](https://github.com/takuti/datadog-anomaly-detector/blob/master/dd_anomaly_detector/datadog_api_helper.py#L22-L23).

A tiny error message to a slack channel does not require Fluent, so I will use [slacweb](https://github.com/satoshi03/slack-python-webhook) python module.
- Check if an environmental variable `os.env['slack']`exists
- If exists, send an error message to the slack url w/ logging

**Comment by takuti** [comment]
@myui Implement slack notification in c38a1a2c90a4bf0e1d7b25fdb5b43a098df37fc4

If a user writes slack webhool url in the .ini file, Datadog-API-related errors will be notified to a specified slack channel w/ logging as:

![2016-08-24 11 21 27](https://cloud.githubusercontent.com/assets/853567/17916287/f20e75f0-69ec-11e6-91af-88159ed0d0c4.png)

In case that this satisfies your requirement, plz close this issue.

**Comment by myui** [comment]
LGTM 👍
